import { createApp } from 'vue';
import {
    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification,
    ElCollapseTransition,
    ElButton,
    ElIcon,
    ElSelect,
    ElOption,
    ElPopover,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem
} from 'element-plus';

import {
    Notebook,
    ChatLineSquare,
    DocumentCopy,
    User,
    Lightning,
    Refresh,
    Goods,
    Key,
    Unlock,
    OfficeBuilding,
    Service,
    Message,
    ArrowDown,
    ArrowUp,
    EditPen,
    Delete,
    MagicStick,
    Paperclip,
    Stopwatch,
    Tickets,
    View,
    Hide,
    Plus,
    Flag,
    CaretBottom,
    CaretTop,
    Search,
    Setting,
    Lock,
    CollectionTag,
    Document,
    Cpu,
    AlarmClock,
    Connection,
    InfoFilled,
    CircleCheck,
    UploadFilled,
    Folder,
    Upload,
    ChatLineRound,
    PriceTag,
    Finished,
    Box,
    More,
    Close,
    Aim,
    CircleClose,
    Camera,
    TopLeft,
    Timer,
    Download,
    MuteNotification,
    FolderAdd,
    FolderChecked,
    ShoppingBag,
    ArrowLeft,
    ArrowRight,
    RefreshRight,
    Check,
    MoreFilled,
    Select,
    ShoppingCart,
    Remove,
    Filter,
    FolderOpened,
    Clock,
    UserFilled,
    Link,
    Star,
    DataAnalysis,
    Calendar
} from '@element-plus/icons-vue';

const icons = [
    Notebook,
    ChatLineSquare,
    User,
    Lightning,
    Refresh,
    Goods,
    Key,
    Unlock,
    OfficeBuilding,
    Service,
    Message,
    ArrowDown,
    ArrowUp,
    EditPen,
    Delete,
    Upload,
    Paperclip,
    Stopwatch,
    Tickets,
    DocumentCopy,
    View,
    Hide,
    Plus,
    Flag,
    CaretBottom,
    CaretTop,
    Search,
    Setting,
    Lock,
    CollectionTag,
    Document,
    Cpu,
    AlarmClock,
    Connection,
    InfoFilled,
    CircleCheck,
    UploadFilled,
    Folder,
    ChatLineRound,
    PriceTag,
    Finished,
    Box,
    More,
    Close,
    Aim,
    CircleClose,
    Camera,
    TopLeft,
    Timer,
    Download,
    MuteNotification,
    MagicStick,
    FolderAdd,
    FolderChecked,
    ShoppingBag,
    ArrowLeft,
    ArrowRight,
    RefreshRight,
    Check,
    MoreFilled,
    Select,
    ShoppingCart,
    Remove,
    Filter,
    FolderOpened,
    Clock,
    UserFilled,
    Link,
    Star,
    DataAnalysis,
    Calendar
];

const app = createApp({});

const plugins = [
    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification,
    ElCollapseTransition,
    ElButton,
    ElIcon,
    ElSelect,
    ElOption,
    ElPopover,
    ElDropdown,
    ElDropdownMenu,
    ElDropdownItem
];

plugins.forEach(plugin => {
    app.use(plugin)
});

icons.forEach(icon => {
    app.component(icon.name, icon);
})

export default app;
